export default {
  id: "freedom-falls",
  title: "Freedom Falls",
  videos: [
    {
      id: "olivia-dean-dive",
      artist: "Olivia Dean",
      title: "Dive",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "The artist Olivia Dean dances down a touristic British street.",
      youTubeId: "NM4e606yFJg",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/01-olivia-dean-dive.js",
    },
    {
      id: "atarashii-gakko-otonablue-the-first-take",
      artist: "ATARASHII GAKKO!",
      title: "OTONABLUE",
      videoType: "livePerformance",
      livePerformanceShow: "The First Take",
      thumbnailSrc: "TODO",
      thumbnailAlt: "Four Japanese girls in schoolgirl outfits leap into the air.",
      youTubeId: "9MNPt-zlz-8",
      descriptionPath:
        "/playlists/2023-04-23-freedom-falls/02-atarashii-gakko-otonablue-the-first-take.js",
    },
    {
      id: "akini-jing-pump-up",
      artist: "Akini Jing",
      title: "Pump Up",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "The artist Akini Jing stands in athletic garb in a workout studio.",
      youTubeId: "grEYQfd7uv0",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/03-akini-jing-pump-up.js",
    },
    {
      id: "xikers-tricky-house",
      artist: "xikers",
      title: "TRICKY HOUSE",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "The xikers team pose in a cavernous garage.",
      youTubeId: "HefrSFeMyPs",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/04-xikers-tricky-house.js",
    },
    {
      id: "alison-goldfrapp-neverstop",
      artist: "Alison Goldfrapp",
      title: "NeverStop",
      videoType: "visualizer",
      videoTypeCustomLabel: "Video Vignette",
      thumbnailSrc: "TODO",
      thumbnailAlt: "The artist Alison Goldfrapp is dressed like a citizen of another world.",
      youTubeId: "Xcsvgsedz20",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/05-alison-goldfrapp-neverstop.js",
    },
    {
      id: "jessie-ware-begin-again",
      artist: "Jessie Ware",
      title: "Begin Again",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "On a stage, the artist Jessie Ware is surrounded by dancers.",
      youTubeId: "yd3C69lVU5w",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/06-jessie-ware-begin-again.js",
    },
    {
      id: "leah-dou-monday",
      artist: "Leah Dou",
      title: "Monday",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "The artist Leah Dou flashes a smile.",
      youTubeId: "vos32LuLjZs",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/07-leah-dou-monday.js",
    },
    {
      id: "rahill-fables",
      artist: "Rahill",
      featuredArtist: "Beck",
      title: "Fables",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "The artist Rahill is much too big to be sitting in a doll house.",
      youTubeId: "Ysf6UULedRk",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/08-rahill-fables.js",
    },
    {
      id: "kaytramine-4eva",
      artist: "KAYTRAMINÉ",
      featuredArtist: "Pharrell Williams",
      title: "4EVA",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "fAPt8AxjPbI",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/09-kaytramine-4eva.js",
    },
    {
      id: "remi-wold-disco-man",
      artist: "Remi Wolf",
      title: "Disco Man",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "V1dtRs_vN6Y",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/10-remi-wold-disco-man.js",
    },
    {
      id: "jack-black-peaches",
      artist: "Jack Black",
      title: "Peaches",
      titleAddendum: "(Directed by Cole Bennett) The Super Mario Bros. Movie",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "aW7bzd8uwyQ",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/11-jack-black-peaches.js",
    },
    {
      id: "ceranda-sugar-rush",
      artist: "CERANDA",
      title: "Sugar Rush",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "LQOib1ny6WY",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/12-ceranda-sugar-rush.js",
    },
    {
      id: "neona-click",
      artist: "Neona",
      title: "Click",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "aGjh-juOyc4",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/13-neona-click.js",
    },
    {
      id: "iri-season",
      artist: "iri",
      title: "Season",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "eQtvqaM1i58",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/14-iri-season.js",
    },
    {
      id: "juno-come-thru",
      artist: "JUNO",
      title: "come thru",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "5oRG_lDPYCk",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/15-juno-come-thru.js",
    },
    {
      id: "lee-chae-yeon-knock",
      artist: "LEE CHAE YEON",
      title: "KNOCK",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "3bnjH5jXxJc",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/16-lee-chae-yeon-knock.js",
    },
    {
      id: "pink-trustfall",
      artist: "P!NK",
      title: "TRUSTFALL",
      videoType: "musicVideo",
      thumbnailSrc:
        "https://i.ytimg.com/vi/D2KE2a5qo0g/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBzC3dFk_g_YF4cUX9rUT8EdzXKXw",
      thumbnailAlt: "With windswept hair, the artist P!NK prepares to dance.",
      youTubeId: "D2KE2a5qo0g",
      descriptionPath: "/playlists/2023-04-23-freedom-falls/17-pink-trustfall.js",
    },
  ],
}
