export default {
  id: "freedom-falls",
  title: "Freedom Falls",
  videos: [
    {
      id: "olivia-dean-dive",
      artist: "Olivia Dean",
      title: "Dive",
      date: "2023-04-14",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/NM4e606yFJg/maxresdefault.jpg",
      thumbnailAlt: "The artist Olivia Dean dances down a touristic British street.",
      youtubeId: "NM4e606yFJg",
      youtubeWidth: 1920,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/01-olivia-dean-dive.js",
    },
    {
      id: "atarashii-gakko-otonablue-the-first-take",
      artist: "ATARASHII GAKKO!",
      title: "OTONABLUE",
      date: "2023-04-07",
      videoType: "livePerformance",
      livePerformanceShow: "The First Take",
      thumbnailSrc: "https://img.youtube.com/vi/9MNPt-zlz-8/maxresdefault.jpg",
      thumbnailAlt: "Four Japanese girls in schoolgirl outfits leap into the air.",
      youtubeId: "9MNPt-zlz-8",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath:
        "/playlists/2023-04-23-freedom-falls/02-atarashii-gakko-otonablue-the-first-take.js",
    },
    {
      id: "akini-jing-pump-up",
      artist: "Akini Jing",
      title: "Pump Up",
      date: "2023-03-21",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/grEYQfd7uv0/maxresdefault.jpg",
      thumbnailAlt: "The artist Akini Jing stands in athletic garb in a workout studio.",
      youtubeId: "grEYQfd7uv0",
      youtubeWidth: 2068,
      youtubeHeight: 1440,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/03-akini-jing-pump-up.js",
    },
    {
      id: "xikers-tricky-house",
      artist: "xikers",
      title: "TRICKY HOUSE",
      date: "2023-03-30",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/HefrSFeMyPs/maxresdefault.jpg",
      thumbnailAlt: "The xikers team pose in a cavernous garage.",
      youtubeId: "HefrSFeMyPs",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/04-xikers-tricky-house.js",
    },
    {
      id: "alison-goldfrapp-neverstop",
      artist: "Alison Goldfrapp",
      title: "NeverStop",
      date: "2023-04-13",
      videoType: "visualizer",
      videoTypeCustomLabel: "Video Vignette",
      thumbnailSrc: "https://img.youtube.com/vi/Xcsvgsedz20/maxresdefault.jpg",
      thumbnailAlt: "The artist Alison Goldfrapp is dressed like a citizen of another world.",
      youtubeId: "Xcsvgsedz20",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/05-alison-goldfrapp-neverstop.js",
    },
    {
      id: "jessie-ware-begin-again",
      artist: "Jessie Ware",
      title: "Begin Again",
      date: "2023-04-13",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/yd3C69lVU5w/maxresdefault.jpg",
      thumbnailAlt: "On a stage, the artist Jessie Ware is surrounded by dancers.",
      youtubeId: "yd3C69lVU5w",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/06-jessie-ware-begin-again.js",
    },
    {
      id: "leah-dou-monday",
      artist: "Leah Dou",
      title: "Monday",
      date: "2023-03-26",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/vos32LuLjZs/maxresdefault.jpg",
      thumbnailAlt: "The artist Leah Dou flashes a smile.",
      youtubeId: "vos32LuLjZs",
      youtubeWidth: 1600,
      youtubeHeight: 1200,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/07-leah-dou-monday.js",
    },
    {
      id: "rahill-fables",
      artist: "Rahill",
      featuredArtist: "Beck",
      title: "Fables",
      date: "2023-03-29",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/Ysf6UULedRk/maxresdefault.jpg",
      thumbnailAlt: "The artist Rahill is much too big to be sitting in a doll house.",
      youtubeId: "Ysf6UULedRk",
      youtubeWidth: 1440,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/08-rahill-fables.js",
    },
    {
      id: "kaytramine-4eva",
      artist: "KAYTRAMINÉ",
      featuredArtist: "Pharrell Williams",
      title: "4EVA",
      date: "2023-04-11",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/fAPt8AxjPbI/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "fAPt8AxjPbI",
      youtubeWidth: 3200,
      youtubeHeight: 1800,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/09-kaytramine-4eva.js",
    },
    {
      id: "remi-wold-disco-man",
      artist: "Remi Wolf",
      title: "Disco Man",
      date: "2020-05-27",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/V1dtRs_vN6Y/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "V1dtRs_vN6Y",
      youtubeWidth: 1920,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/10-remi-wold-disco-man.js",
    },
    {
      id: "jack-black-peaches",
      artist: "Jack Black",
      title: "Peaches",
      titleAddendum: "(Directed by Cole Bennett) The Super Mario Bros. Movie",
      date: "2023-04-07",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/aW7bzd8uwyQ/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "aW7bzd8uwyQ",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/11-jack-black-peaches.js",
    },
    {
      id: "ceranda-sugar-rush",
      artist: "CERANDA",
      title: "Sugar Rush",
      date: "2023-03-22",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/LQOib1ny6WY/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "LQOib1ny6WY",
      youtubeWidth: 2880,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/12-ceranda-sugar-rush.js",
    },
    {
      id: "neona-click",
      artist: "Neona",
      title: "Click",
      date: "2023-04-06",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/aGjh-juOyc4/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "aGjh-juOyc4",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/13-neona-click.js",
    },
    {
      id: "iri-season",
      artist: "iri",
      title: "Season",
      date: "2023-04-18",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/eQtvqaM1i58/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "eQtvqaM1i58",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/14-iri-season.js",
    },
    {
      id: "juno-come-thru",
      artist: "JUNO",
      title: "come thru",
      date: "2023-04-11",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/5oRG_lDPYCk/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "5oRG_lDPYCk",
      youtubeWidth: 2880,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/15-juno-come-thru.js",
    },
    {
      id: "lee-chae-yeon-knock",
      artist: "LEE CHAE YEON",
      title: "KNOCK",
      date: "2023-04-12",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/3bnjH5jXxJc/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "3bnjH5jXxJc",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/16-lee-chae-yeon-knock.js",
    },
    {
      id: "pink-trustfall",
      artist: "P!NK",
      title: "TRUSTFALL",
      date: "2023-01-27",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/D2KE2a5qo0g/maxresdefault.jpg",
      thumbnailAlt: "With windswept hair, the artist P!NK prepares to dance.",
      youtubeId: "D2KE2a5qo0g",
      youtubeWidth: 3840,
      youtubeHeight: 1556,
      descriptionPath: "/playlists/2023-04-23-freedom-falls/17-pink-trustfall.js",
    },
  ],
}
