export default [
  {
    id: "the-chemical-brothers-skipping-like-a-stone",
    artist: "The Chemical Brothers",
    title: "Skipping Like A Stone",
    featuredArtist: "Beck",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youtubeId: "nRtxogXp8sY",
    descriptionPath: "/videos/the-chemical-brothers-skipping-like-a-stone.js",
  },
  {
    id: "annatoria-the-divide",
    artist: "Annatoria",
    title: "The Divide",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youtubeId: "3tixhS3ilNw",
    descriptionPath: "/videos/annatoria-the-divide.js",
  },
  {
    id: "rimon-i-choose-u",
    artist: "RIMON",
    featuredArtist: "RINI",
    title: "I Choose U",
    videoType: "musicVideo",
    thumbnailSrc:
      "https://i.ytimg.com/vi/W1yyy-CkGqY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD5LBvddMgEbfZVzD85sku1DtbEHw",
    thumbnailAlt:
      "A man holds the business end of a bow and arrow and the artist RIMON pulls the drawstring back, ready to fire it into his heart.",
    youtubeId: "W1yyy-CkGqY",
    descriptionPath: "/videos/rimon-i-choose-u.js",
  },
  {
    id: "kirinji-twilight",
    artist: "KIRINJI",
    featuredArtist: "Maika Loubté",
    title: "Twilight",
    videoType: "musicVideo",
    thumbnailAlt: "A despondent young woman in a dark city gazes at a toy carousel.",
    youtubeId: "fzGaTj0LdeM",
    descriptionPath: "/videos/kirinji-twilight.js",
  },
  {
    id: "hybs-would-you-mind",
    artist: "HYBS",
    title: "Would You Mind",
    videoType: "musicVideo",
    thumbnailAlt: "A girl in a cafe smiles shyly at someone.",
    youtubeId: "WW6VE7ROcyA",
    descriptionPath: "/videos/hybs-would-you-mind.js",
  },
  {
    id: "nsp-welcome-to-my-parents-house",
    artist: "Ninja Sex Party",
    title: "Welcome To My Parents' House",
    videoType: "musicVideo",
    thumbnailAlt: "A cartoon gal and guy smile sexily.",
    youtubeId: "3YXUWWZJXpE",
    descriptionPath: "/videos/nsp-welcome-to-my-parents-house.js",
  },
  {
    id: "fka-twigs-holy-terrain",
    artist: "FKA twigs",
    featuredArtist: "Future",
    title: "holy terrain",
    videoType: "musicVideo",
    thumbnailAlt:
      "The artist FKA twigs looks profoundly stoned with her right eye red and her left eye blue.",
    youtubeId: "WEJRyBWpuvA",
    descriptionPath: "/videos/fka-twigs-holy-terrain.js",
  },
  {
    id: "amtrac-nobody-else",
    artist: "Amtrac",
    title: "Nobody Else",
    videoType: "musicVideo",
    thumbnailAlt: "A tiny robot hides in the bushes.",
    youtubeId: "nE1ZXUE_BXU",
    descriptionPath: "/videos/amtrac-nobody-else.js",
  },
  {
    id: "seulgi-anywhere-but-home",
    artist: "Seulgi",
    title: "Anywhere But Home",
    videoType: "musicVideo",
    videoTypeCustomLabel: "Special Film",
    thumbnailAlt:
      "In nighttime streets the artist Seulgi stares down the camera like a wild animal.",
    youtubeId: "2hVimOZHbOI",
    descriptionPath: "/videos/seulgi-anywhere-but-home.js",
  },
]
