export default [
  {
    id: "maye-tu",
    artist: "maye",
    title: "Tú",
    date: "2019-09-13",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/jhQ4WVJwz7w/maxresdefault.jpg",
    thumbnailAlt: "TODO",
    youtubeId: "jhQ4WVJwz7w",
    youtubeWidth: 3840,
    youtubeHeight: 2160,
    descriptionPath: "/videos/maye-tu.js",
  },
  {
    id: "the-chemical-brothers-skipping-like-a-stone",
    artist: "The Chemical Brothers",
    featuredArtist: "Beck",
    title: "Skipping Like A Stone",
    date: "2023-09-20",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/nRtxogXp8sY/maxresdefault.jpg",
    thumbnailAlt: "TODO",
    youtubeId: "nRtxogXp8sY",
    youtubeWidth: 1920,
    youtubeHeight: 1080,
    descriptionPath: "/videos/the-chemical-brothers-skipping-like-a-stone.js",
  },
  {
    id: "annatoria-the-divide",
    artist: "Annatoria",
    title: "The Divide",
    date: "2022-10-06",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/3tixhS3ilNw/maxresdefault.jpg",
    thumbnailAlt: "TODO",
    youtubeId: "3tixhS3ilNw",
    youtubeWidth: 3840,
    youtubeHeight: 2160,
    descriptionPath: "/videos/annatoria-the-divide.js",
  },
  {
    id: "rimon-i-choose-u",
    artist: "RIMON",
    featuredArtist: "RINI",
    title: "I Choose U",
    date: "2023-03-24",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/W1yyy-CkGqY/maxresdefault.jpg",
    thumbnailAlt:
      "A man holds the business end of a bow and arrow and the artist RIMON pulls the drawstring back, ready to fire it into his heart.",
    youtubeId: "W1yyy-CkGqY",
    youtubeWidth: 2112,
    youtubeHeight: 1296,
    descriptionPath: "/videos/rimon-i-choose-u.js",
  },
  {
    id: "kirinji-twilight",
    artist: "KIRINJI",
    featuredArtist: "Maika Loubté",
    title: "Twilight",
    date: "2021-12-07",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/fzGaTj0LdeM/maxresdefault.jpg",
    thumbnailAlt: "A despondent young woman in a dark city gazes at a toy carousel.",
    youtubeWidth: 3840,
    youtubeHeight: 1608,
    youtubeId: "fzGaTj0LdeM",
    descriptionPath: "/videos/kirinji-twilight.js",
  },
  {
    id: "hybs-would-you-mind",
    artist: "HYBS",
    title: "Would You Mind",
    date: "2022-09-03",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/WW6VE7ROcyA/maxresdefault.jpg",
    thumbnailAlt: "A girl in a cafe smiles shyly at someone.",
    youtubeId: "WW6VE7ROcyA",
    youtubeWidth: 1920,
    youtubeHeight: 1080,
    descriptionPath: "/videos/hybs-would-you-mind.js",
  },
  {
    id: "nsp-welcome-to-my-parents-house",
    artist: "Ninja Sex Party",
    title: "Welcome To My Parents' House",
    date: "2020-11-23",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/3YXUWWZJXpE/maxresdefault.jpg",
    thumbnailAlt: "A cartoon gal and guy smile sexily.",
    youtubeId: "3YXUWWZJXpE",
    youtubeWidth: 1920,
    youtubeHeight: 1080,
    descriptionPath: "/videos/nsp-welcome-to-my-parents-house.js",
  },
  {
    id: "fka-twigs-holy-terrain",
    artist: "FKA twigs",
    featuredArtist: "Future",
    date: "2019-09-09",
    title: "holy terrain",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/WEJRyBWpuvA/maxresdefault.jpg",
    thumbnailAlt:
      "The artist FKA twigs looks profoundly stoned with her right eye red and her left eye blue.",
    youtubeId: "WEJRyBWpuvA",
    youtubeWidth: 1920,
    youtubeHeight: 1080,
    descriptionPath: "/videos/fka-twigs-holy-terrain.js",
  },
  {
    id: "amtrac-nobody-else",
    artist: "Amtrac",
    title: "Nobody Else",
    date: "2023-02-03",
    videoType: "musicVideo",
    thumbnailSrc: "https://img.youtube.com/vi/nE1ZXUE_BXU/maxresdefault.jpg",
    thumbnailAlt: "A tiny robot hides in the bushes.",
    youtubeId: "nE1ZXUE_BXU",
    youtubeWidth: 2048,
    youtubeHeight: 872,
    descriptionPath: "/videos/amtrac-nobody-else.js",
  },
  {
    id: "seulgi-anywhere-but-home",
    artist: "Seulgi",
    title: "Anywhere But Home",
    date: "2023-02-10",
    videoType: "musicVideo",
    videoTypeCustomLabel: "Special Film",
    thumbnailSrc: "https://img.youtube.com/vi/2hVimOZHbOI/maxresdefault.jpg",
    thumbnailAlt:
      "In nighttime streets the artist Seulgi stares down the camera like a wild animal.",
    youtubeId: "2hVimOZHbOI",
    youtubeWidth: 1440,
    youtubeHeight: 1080,
    descriptionPath: "/videos/seulgi-anywhere-but-home.js",
  },
]
