export default {
  id: "bank-of-earth",
  title: "BANK OF EARTH / NO WITHDRAWAL",
  needsContentAdvisory: true,
  videos: [
    {
      id: "generation-loss-connected",
      artist: "Generation Loss",
      title: "Connected.",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "9N8Y8zmvTyE",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/01-generation-loss-connected.js",
    },
    {
      id: "aespa-im-unhappy",
      artist: "aespa",
      title: "I'm Unhappy",
      videoType: "musicVideo",
      videoTypeCustomLabel: "Track Video",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "CC7OrEx5H4U",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/02-aespa-im-unhappy.js",
    },
    {
      id: "ice-nine-kills-assault-and-batteries",
      artist: "Ice Nine Kills",
      title: "Assault & Batteries",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "j8vKjIakHbA",
      descriptionPath:
        "/playlists/2023-06-03-bank-of-earth/03-ice-nine-kills-assault-and-batteries.js",
    },
    {
      id: "king-gizzard-and-the-lizard-wizard-gila-monster",
      artist: "King Gizzard & The Lizard Wizard",
      title: "Gila Monster",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "YQX2CsMCB9M",
      descriptionPath:
        "/playlists/2023-06-03-bank-of-earth/04-king-gizzard-and-the-lizard-wizard-gila-monster.js",
    },
    {
      id: "mette-mamas-eyes",
      artist: "METTE",
      title: "Mama's Eyes",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "gi9OBRzbMNI",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/05-mette-mamas-eyes.js",
    },
    {
      id: "mura-masa-whenever-i-want",
      artist: "Mura Masa",
      title: "Whenever I Want",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "mQL-xrUy_eM",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/06-mura-masa-whenever-i-want.js",
    },
    {
      id: "code-kunst-55",
      artist: "CODE KUNST",
      title: "55",
      featuredArtists: ["Yerin Baek", "WENDY"],
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "xHnuscnWaRk",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/07-code-kunst-55.js",
    },
    {
      id: "harry-styles-satellite",
      artist: "Harry Styles",
      title: "Satellite",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "bGZplqeIb3w",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/08-harry-styles-satellite.js",
    },
    {
      id: "aespa-welcome-to-my-world",
      artist: "aespa",
      featuredArtist: "nævis",
      title: "Welcome To MY World",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "0xdB_vo4r2c",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/09-aespa-welcome-to-my-world.js",
    },
    {
      id: "greta-van-fleet-meeting-the-master",
      artist: "Greta Van Fleet",
      title: "Meeting The Master",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "SFFKed1Dt4I",
      descriptionPath:
        "/playlists/2023-06-03-bank-of-earth/10-greta-van-fleet-meeting-the-master.js",
    },
    {
      id: "niki-backburner",
      artist: "NIKI",
      title: "Backburner",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "BBpIV9A1PXc",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/11-niki-backburner.js",
    },
    {
      id: "tatsuro-yamashita-sparkle",
      artist: "TATSURO YAMASHITA",
      title: "SPARKLE",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "pqobRu9aR3M",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/12-tatsuro-yamashita-sparkle.js",
    },
    {
      id: "rita-ora-praising-you",
      artist: "Rita Ora",
      featuredArtist: "Fatboy Slim",
      title: "Praising You",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youTubeId: "_Sz7fhThrS4",
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/13-rita-ora-praising-you.js",
    },
  ],
}
