export default {
  id: "bank-of-earth",
  title: "BANK OF EARTH / NO WITHDRAWAL",
  needsContentAdvisory: true,
  videos: [
    {
      id: "generation-loss-connected",
      artist: "Generation Loss",
      title: "Connected.",
      date: "2023-05-01",
      videoType: "foundFootage",
      thumbnailSrc: "https://img.youtube.com/vi/9N8Y8zmvTyE/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "9N8Y8zmvTyE",
      youtubeWidth: 1440,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/01-generation-loss-connected.js",
    },
    {
      id: "aespa-im-unhappy",
      artist: "aespa",
      title: "I'm Unhappy",
      date: "2023-05-02",
      videoType: "musicVideo",
      videoTypeCustomLabel: "Track Video",
      thumbnailSrc: "https://img.youtube.com/vi/CC7OrEx5H4U/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "CC7OrEx5H4U",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/02-aespa-im-unhappy.js",
    },
    {
      id: "ice-nine-kills-assault-and-batteries",
      artist: "Ice Nine Kills",
      title: "Assault & Batteries",
      date: "2021-08-09",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/j8vKjIakHbA/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "j8vKjIakHbA",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath:
        "/playlists/2023-06-03-bank-of-earth/03-ice-nine-kills-assault-and-batteries.js",
    },
    {
      id: "king-gizzard-and-the-lizard-wizard-gila-monster",
      artist: "King Gizzard & The Lizard Wizard",
      title: "Gila Monster",
      date: "2023-05-16",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/YQX2CsMCB9M/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "YQX2CsMCB9M",
      youtubeWidth: 3840,
      youtubeHeight: 1616,
      descriptionPath:
        "/playlists/2023-06-03-bank-of-earth/04-king-gizzard-and-the-lizard-wizard-gila-monster.js",
    },
    {
      id: "mette-mamas-eyes",
      artist: "METTE",
      title: "Mama's Eyes",
      date: "2023-05-03",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/gi9OBRzbMNI/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "gi9OBRzbMNI",
      youtubeWidth: 1620,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/05-mette-mamas-eyes.js",
    },
    {
      id: "mura-masa-whenever-i-want",
      artist: "Mura Masa",
      title: "Whenever I Want",
      date: "2023-04-03",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/mQL-xrUy_eM/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "mQL-xrUy_eM",
      youtubeWidth: 1920,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/06-mura-masa-whenever-i-want.js",
    },
    {
      id: "code-kunst-55",
      artist: "CODE KUNST",
      featuredArtists: ["Yerin Baek", "WENDY"],
      title: "55",
      date: "2023-03-08",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/xHnuscnWaRk/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "xHnuscnWaRk",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/07-code-kunst-55.js",
    },
    {
      id: "harry-styles-satellite",
      artist: "Harry Styles",
      title: "Satellite",
      date: "2023-05-03",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/bGZplqeIb3w/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "bGZplqeIb3w",
      youtubeWidth: 3176,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/08-harry-styles-satellite.js",
    },
    {
      id: "aespa-welcome-to-my-world",
      artist: "aespa",
      featuredArtist: "nævis",
      title: "Welcome To MY World",
      date: "2023-05-02",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/0xdB_vo4r2c/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "0xdB_vo4r2c",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/09-aespa-welcome-to-my-world.js",
    },
    {
      id: "greta-van-fleet-meeting-the-master",
      artist: "Greta Van Fleet",
      title: "Meeting The Master",
      date: "2023-05-03",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/SFFKed1Dt4I/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "SFFKed1Dt4I",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath:
        "/playlists/2023-06-03-bank-of-earth/10-greta-van-fleet-meeting-the-master.js",
    },
    {
      id: "niki-backburner",
      artist: "NIKI",
      title: "Backburner",
      date: "2023-05-15",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/BBpIV9A1PXc/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "BBpIV9A1PXc",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/11-niki-backburner.js",
    },
    {
      id: "tatsuro-yamashita-sparkle",
      artist: "TATSURO YAMASHITA",
      title: "SPARKLE",
      date: "2023-04-27",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/pqobRu9aR3M/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "pqobRu9aR3M",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/12-tatsuro-yamashita-sparkle.js",
    },
    {
      id: "rita-ora-praising-you",
      artist: "Rita Ora",
      featuredArtist: "Fatboy Slim",
      title: "Praising You",
      date: "2023-04-28",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/_Sz7fhThrS4/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "_Sz7fhThrS4",
      youtubeWidth: 1920,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2023-06-03-bank-of-earth/13-rita-ora-praising-you.js",
    },
  ],
}
