export default [
  {
    id: "billlie-eunoia",
    artist: "Billlie",
    title: "EUNOIA",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "MVjQIQGqNFM",
    fileName: "billlie-eunoia.js",
  },
  {
    id: "olivia-dean-dive",
    artist: "Olivia Dean",
    title: "Dive",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "NM4e606yFJg",
    fileName: "olivia-dean-dive.js",
  },
  {
    id: "atarashii-gakko-otonablue-the-first-take",
    artist: "ATARASHII GAKKO!",
    title: "OTONABLUE",
    videoType: "livePerformance",
    livePerformanceShow: "The First Take",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "9MNPt-zlz-8",
    fileName: "atarashii-gakko-otonablue-the-first-take.js",
  },
  {
    id: "akini-jing-pump-up",
    artist: "Akini Jing",
    title: "Pump Up",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "grEYQfd7uv0",
    fileName: "akini-jing-pump-up.js",
  },
  {
    id: "xikers-tricky-house",
    artist: "xikers",
    title: "TRICKY HOUSE",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "HefrSFeMyPs",
    fileName: "xikers-tricky-house.js",
  },
  {
    id: "alison-goldfrapp-neverstop",
    artist: "Alison Goldfrapp",
    title: "NeverStop",
    videoType: "visualizer",
    videoTypeCustomLabel: "Video Vignette",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "Xcsvgsedz20",
    fileName: "alison-goldfrapp-neverstop.js",
  },
  {
    id: "jessie-ware-begin-again",
    artist: "Jessie Ware",
    title: "Begin Again",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "yd3C69lVU5w",
    fileName: "jessie-ware-begin-again.js",
  },
  {
    id: "leah-dou-monday",
    artist: "Leah Dou",
    title: "Monday",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "vos32LuLjZs",
    fileName: "leah-dou-monday.js",
  },
  {
    id: "rahill-fables",
    artist: "Rahill",
    featuredArtist: "Beck",
    title: "Fables",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "Ysf6UULedRk",
    fileName: "rahill-fables.js",
  },
  {
    id: "alice-phoebe-lou-shelter",
    artist: "Alice Phoebe Lou",
    title: "Shelter",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "URtqWrMgn-Q",
    fileName: "alice-phoebe-lou-shelter.js",
  },
  {
    id: "kaytramine-4eva",
    artist: "KAYTRAMINÉ",
    featuredArtist: "Pharrell Williams",
    title: "4EVA",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "fAPt8AxjPbI",
    fileName: "kaytramine-4eva.js",
  },
  {
    id: "remi-wold-disco-man",
    artist: "Remi Wolf",
    title: "Disco Man",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "V1dtRs_vN6Y",
    fileName: "remi-wold-disco-man.js",
  },
  {
    id: "jack-black-peaches",
    artist: "Jack Black",
    title: "Peaches",
    titleAddendum: "(Directed by Cole Bennett) The Super Mario Bros. Movie",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "aW7bzd8uwyQ",
    fileName: "jack-black-peaches.js",
  },
  {
    id: "ceranda-sugar-rush",
    artist: "CERANDA",
    title: "Sugar Rush",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "LQOib1ny6WY",
    fileName: "ceranda-sugar-rush.js",
  },
  {
    id: "neona-click",
    artist: "Neona",
    title: "Click",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "aGjh-juOyc4",
    fileName: "neona-click.js",
  },
  {
    id: "iri-season",
    artist: "iri",
    title: "Season",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "eQtvqaM1i58",
    fileName: "iri-season.js",
  },
  {
    id: "juno-come-thru",
    artist: "JUNO",
    title: "come thru",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "5oRG_lDPYCk",
    fileName: "juno-come-thru.js",
  },
  {
    id: "lee-chae-yeon-knock",
    artist: "LEE CHAE YEON",
    title: "KNOCK",
    videoType: "musicVideo",
    thumbnailSrc: "TODO",
    thumbnailAlt: "TODO",
    youTubeId: "3bnjH5jXxJc",
    fileName: "lee-chae-yeon-knock.js",
  },
  {
    id: "pink-trustfall",
    artist: "P!NK",
    title: "TRUSTFALL",
    videoType: "musicVideo",
    thumbnailSrc:
      "https://i.ytimg.com/vi/D2KE2a5qo0g/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBzC3dFk_g_YF4cUX9rUT8EdzXKXw",
    thumbnailAlt: "With windswept hair, the artist P!NK prepares to dance.",
    youTubeId: "D2KE2a5qo0g",
    fileName: "pink-trustfall.js",
  },
  {
    id: "rimon-i-choose-u",
    artist: "RIMON",
    featuredArtist: "RINI",
    title: "I Choose U",
    videoType: "musicVideo",
    thumbnailSrc:
      "https://i.ytimg.com/vi/W1yyy-CkGqY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD5LBvddMgEbfZVzD85sku1DtbEHw",
    thumbnailAlt:
      "A man holds the business end of a bow and arrow and the artist RIMON pulls the drawstring back, ready to fire it into his heart.",
    youTubeId: "W1yyy-CkGqY",
    fileName: "rimon-i-choose-u.js",
  },
  {
    id: "kirinji-twilight",
    artist: "KIRINJI",
    featuredArtist: "Maika Loubté",
    title: "Twilight",
    videoType: "musicVideo",
    thumbnailAlt: "A despondent young woman in a dark city gazes at a toy carousel.",
    youTubeId: "fzGaTj0LdeM",
    fileName: "kirinji-twilight.js",
  },
  {
    id: "hybs-would-you-mind",
    artist: "HYBS",
    title: "Would You Mind",
    videoType: "musicVideo",
    thumbnailAlt: "A girl in a cafe smiles shyly at someone.",
    youTubeId: "WW6VE7ROcyA",
    fileName: "hybs-would-you-mind.js",
  },
  {
    id: "nsp-welcome-to-my-parents-house",
    artist: "Ninja Sex Party",
    title: "Welcome To My Parents' House",
    videoType: "musicVideo",
    thumbnailAlt: "A cartoon gal and guy smile sexily.",
    youTubeId: "3YXUWWZJXpE",
    fileName: "nsp-welcome-to-my-parents-house.js",
  },
  {
    id: "fka-twigs-holy-terrain",
    artist: "FKA twigs",
    featuredArtist: "Future",
    title: "holy terrain",
    videoType: "musicVideo",
    thumbnailAlt:
      "The artist FKA twigs looks profoundly stoned with her right eye red and her left eye blue.",
    youTubeId: "WEJRyBWpuvA",
    fileName: "fka-twigs-holy-terrain.js",
  },
  {
    id: "amtrac-nobody-else",
    artist: "Amtrac",
    title: "Nobody Else",
    videoType: "musicVideo",
    thumbnailAlt: "A tiny robot hides in the bushes.",
    youTubeId: "nE1ZXUE_BXU",
    fileName: "amtrac-nobody-else.js",
  },
  {
    id: "seulgi-anywhere-but-home",
    artist: "Seulgi",
    title: "Anywhere But Home",
    videoType: "musicVideo",
    videoTypeCustomLabel: "Special Film",
    thumbnailAlt:
      "In nighttime streets the artist Seulgi stares down the camera like a wild animal.",
    youTubeId: "2hVimOZHbOI",
    fileName: "seulgi-anywhere-but-home.js",
  },
]
