export default {
  id: "love-letter",
  title: "Love Letter",
  videos: [
    {
      id: "lute-finding-self",
      artist: "Lute",
      title: "Finding Self",
      date: "2022-10-31",
      videoType: "musicVideo",
      videoTypeCustomLabel: "Short Film",
      thumbnailSrc: "https://img.youtube.com/vi/FRGJnz6w4-A/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "FRGJnz6w4-A",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2022-10-31-love-letter/01-lute-finding-self.js",
    },
    {
      id: "salvatore-ganacci-take-me-to-america",
      artist: "Salvatore Ganacci",
      title: "Take Me To America",
      date: "2022-10-27",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/PcR8I-7oCnU/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "PcR8I-7oCnU",
      youtubeWidth: 1920,
      youtubeHeight: 1080,
      descriptionPath:
        "/playlists/2022-10-31-love-letter/02-salvatore-ganacci-take-me-to-america.js",
    },
    {
      id: "the-blaze-dreamer",
      artist: "The Blaze",
      title: "DREAMER",
      date: "2022-11-09",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/G6K_hkVdQgw/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "G6K_hkVdQgw",
      youtubeWidth: 1920,
      youtubeHeight: 1080,
      descriptionPath: "/playlists/2022-10-31-love-letter/03-the-blaze-dreamer.js",
    },
    {
      id: "king-gnu-boy",
      artist: "King Gnu",
      title: "BOY",
      date: "2021-10-15",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/n0QNaym0jDI/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "n0QNaym0jDI",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2022-10-31-love-letter/04-king-gnu-boy.js",
    },
    {
      id: "weyes-blood-grapevine",
      artist: "Weyes Blood",
      title: "Grapevine",
      date: "2022-10-28",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/MNDlMe4nuWw/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "MNDlMe4nuWw",
      youtubeWidth: 2560,
      youtubeHeight: 1072,
      descriptionPath: "/playlists/2022-10-31-love-letter/05-weyes-blood-grapevine.js",
    },
    {
      id: "atarashii-gakko-hanako",
      artist: "ATARASHII GAKKO!",
      title: "HANAKO",
      date: "2022-10-31",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/IXfnrInr4xQ/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "IXfnrInr4xQ",
      youtubeWidth: 2880,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2022-10-31-love-letter/06-atarashii-gakko-hanako.js",
    },
    {
      id: "slom-anirago",
      artist: "Slom",
      featuredArtist: "Zion.T",
      title: "ANIRAGO",
      date: "2022-10-27",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/K_eRv94tcec/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "K_eRv94tcec",
      youtubeWidth: 3840,
      youtubeHeight: 2160,
      descriptionPath: "/playlists/2022-10-31-love-letter/07-slom-anirago.js",
    },
    {
      id: "odesza-love-letter",
      artist: "ODESZA",
      featuredArtist: "The Knocks",
      title: "Love Letter",
      titleAddendum: "Starring Simone Ashley",
      date: "2022-08-04",
      videoType: "musicVideo",
      thumbnailSrc: "https://img.youtube.com/vi/ZkwoBbkSh7k/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "ZkwoBbkSh7k",
      youtubeWidth: 3200,
      youtubeHeight: 1800,
      descriptionPath: "/playlists/2022-10-31-love-letter/08-odesza-love-letter.js",
    },
    {
      id: "dodie-hot-mess-ep",
      artist: "dodie",
      title: "Hot Mess EP",
      date: "2022-10-14",
      videoType: "livePerformance",
      livePerformanceCustomLabel: "full film, live from the attic",
      thumbnailSrc: "https://img.youtube.com/vi/GDfr8yQ34Bg/maxresdefault.jpg",
      thumbnailAlt: "TODO",
      youtubeId: "GDfr8yQ34Bg",
      youtubeWidth: 2048,
      youtubeHeight: 1152,
      descriptionPath: "/playlists/2022-10-31-love-letter/09-dodie-hot-mess-ep.js",
    },
  ],
}
