export default {
  id: "love-letter",
  title: "Love Letter",
  videos: [
    {
      id: "lute-finding-self",
      artist: "Lute",
      title: "Finding Self",
      videoType: "musicVideo",
      videoTypeCustomLabel: "Short Film",
      thumbnailSrc:
        "https://i.ytimg.com/vi/FRGJnz6w4-A/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfl73HlpJXjaAtk-xFp62ZeWC_4w",
      thumbnailAlt: "TODO",
      youtubeId: "FRGJnz6w4-A",
      descriptionPath: "/playlists/2022-10-31-love-letter/01-lute-finding-self.js",
    },
    {
      id: "salvatore-ganacci-take-me-to-america",
      artist: "Salvatore Ganacci",
      title: "Take Me To America",
      videoType: "musicVideo",
      thumbnailSrc:
        "https://i.ytimg.com/vi/PcR8I-7oCnU/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIF0oTzAP&rs=AOn4CLDXPEoxfcKsC9DcokOOUAT7gHXR6w",
      thumbnailAlt: "TODO",
      youtubeId: "PcR8I-7oCnU",
      descriptionPath:
        "/playlists/2022-10-31-love-letter/02-salvatore-ganacci-take-me-to-america.js",
    },
    {
      id: "the-blaze-dreamer",
      artist: "The Blaze",
      title: "DREAMER",
      videoType: "musicVideo",
      thumbnailSrc:
        "https://i.ytimg.com/vi/G6K_hkVdQgw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCiwnbqQ7CZO9tBBGZNQHrK9Fizxg",
      thumbnailAlt: "TODO",
      youtubeId: "G6K_hkVdQgw",
      descriptionPath: "/playlists/2022-10-31-love-letter/03-the-blaze-dreamer.js",
    },
    {
      id: "king-gnu-boy",
      artist: "King Gnu",
      title: "BOY",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youtubeId: "n0QNaym0jDI",
      descriptionPath: "/playlists/2022-10-31-love-letter/04-king-gnu-boy.js",
    },
    {
      id: "weyes-blood-grapevine",
      artist: "Weyes Blood",
      title: "Grapevine",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youtubeId: "MNDlMe4nuWw",
      descriptionPath: "/playlists/2022-10-31-love-letter/05-weyes-blood-grapevine.js",
    },
    {
      id: "atarashii-gakko-hanako",
      artist: "ATARASHII GAKKO!",
      title: "HANAKO",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youtubeId: "IXfnrInr4xQ",
      descriptionPath: "/playlists/2022-10-31-love-letter/06-atarashii-gakko-hanako.js",
    },
    {
      id: "slom-anirago",
      artist: "Slom",
      featuredArtist: "Zion.T",
      title: "ANIRAGO",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youtubeId: "K_eRv94tcec",
      descriptionPath: "/playlists/2022-10-31-love-letter/07-slom-anirago.js",
    },
    {
      id: "odesza-love-letter",
      artist: "ODESZA",
      featuredArtist: "The Knocks",
      title: "Love Letter",
      titleAddendum: "Starring Simone Ashley",
      videoType: "musicVideo",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youtubeId: "ZkwoBbkSh7k",
      descriptionPath: "/playlists/2022-10-31-love-letter/08-odesza-love-letter.js",
    },
    {
      id: "dodie-hot-mess-ep",
      artist: "dodie",
      title: "Hot Mess EP",
      videoType: "livePerformance",
      livePerformanceCustomLabel: "full film, live from the attic",
      thumbnailSrc: "TODO",
      thumbnailAlt: "TODO",
      youtubeId: "GDfr8yQ34Bg",
      descriptionPath: "/playlists/2022-10-31-love-letter/09-dodie-hot-mess-ep.js",
    },
  ],
}
